In [113]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [114]:
mp_key = "txVH20lqfEIM4Yxb2k5ptbih3BpgcIsN"
mp_id = "mp-1008680"

In [115]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Structure symmetry 1


In [116]:
i_atom = 7
i_symmop = 2

In [117]:
symmop = symmops[i_symmop - 1]
print("L'opération de symmétrie : \n",symmop)

L'opération de symmétrie : 
 Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [118]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
pos_final = symmop.operate(pos_init)

print("Position initiale de l'atome:",pos_init)
print("Position finale après l'opération de symétrie:", pos_final)


Position initiale de l'atome: [0.5 0.  0. ]
Position finale après l'opération de symétrie: [ 0.  -0.5  0. ]


In [119]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print("Indice de l'atome résultant:", j_atom)
print("Coordonnées fractionnaires de l'atome résultant:", conv_struc.sites[j_atom - 1].frac_coords)

Indice de l'atome résultant: 6
Coordonnées fractionnaires de l'atome résultant: [0.  0.5 0. ]


In [120]:
#affichage structure initiale

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

#opération de symmétrie

view.script('select titanium; color lightsalmon')
view.script('select germanium; color gold')
view.script('select platinum; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Structure symmetry 2



In [121]:
i_atom = 4
i_symmop = 5

In [122]:
symmop = symmops[i_symmop - 1]
print("L'opération de symmétrie : \n",symmop)

L'opération de symmétrie : 
 Rot:
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [123]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
pos_final = symmop.operate(pos_init)

print("Position initiale de l'atome:",pos_init)
print("Position finale après l'opération de symétrie:", pos_final)


Position initiale de l'atome: [0.5 0.5 0. ]
Position finale après l'opération de symétrie: [ 0.5 -0.5  0. ]


In [124]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print("Indice de l'atome résultant:", j_atom)
print("Coordonnées fractionnaires de l'atome résultant:", conv_struc.sites[j_atom - 1].frac_coords)

Indice de l'atome résultant: 4
Coordonnées fractionnaires de l'atome résultant: [0.5 0.5 0. ]


In [125]:
#affichage structure initiale

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

#opération de symmétrie

view.script('select titanium; color lightsalmon')
view.script('select germanium; color gold')
view.script('select platinum; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Structure symmetry 3



In [126]:
i_atom = 8
i_symmop = 3

In [127]:
symmop = symmops[i_symmop - 1]
print("L'opération de symmétrie : \n",symmop)

L'opération de symmétrie : 
 Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


In [128]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
pos_final = symmop.operate(pos_init)

print("Position initiale de l'atome:",pos_init)
print("Position finale après l'opération de symétrie:", pos_final)


Position initiale de l'atome: [0.5 0.5 0.5]
Position finale après l'opération de symétrie: [-0.5 -0.5  0.5]


In [129]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print("Indice de l'atome résultant:", j_atom)
print("Coordonnées fractionnaires de l'atome résultant:", conv_struc.sites[j_atom - 1].frac_coords)

Indice de l'atome résultant: 8
Coordonnées fractionnaires de l'atome résultant: [0.5 0.5 0.5]


In [130]:
#affichage structure initiale

view = quick_view(prim_struc, "packed", conventional = True)
display(view)

#opération de symmétrie

view.script('select titanium; color lightsalmon')
view.script('select germanium; color gold')
view.script('select platinum; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))